version: 1.1.{build}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
  - README.md
  - CHANGELOG.md
  - .editorconfig
  - .gitignore
  - renovate.json

max_jobs: 1


image: Visual Studio 2017

environment:
  MAVEN_VERSION: 3.6.1
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
- ps: |
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    if (!(Test-Path -Path "C:\maven" )) {
      Write-Host "Downloading Maven $env:MAVEN_VERSION"
      (new-object System.Net.WebClient).DownloadFile("https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip", 'C:\maven-bin.zip')
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
    }
- cmd: SET M2_HOME=C:\maven\apache-maven-%MAVEN_VERSION%
- cmd: PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%;
- cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
- cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
- cmd: mvn --version
- cmd: java -version

init:
  - git config --global core.autocrlf input

build_script:
- mvn -B -V -Dchangelist=-%APPVEYOR_BUILD_NUMBER% clean verify

artifacts:
- path: target/jobcacher.hpi
  
cache:
- C:\maven\ -> .appveyor.yml
- C:\Users\appveyor\.m2\ -> pom.xml